In [5]:
!pip3 install numpy

In [6]:
import numpy as np

In [7]:
np.__version__

'1.19.2'

In [8]:
a = np.array([0,1,2,3,4])

In [9]:
a

array([0, 1, 2, 3, 4])

In [11]:
b = np.array([5,6,7])

In [12]:
b

array([5, 6, 7])

In [18]:
np.arange(0,21,1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [21]:
np.arange(0,20,1)
print("endpoint True:",a)

endpoint True: [0 1 2 3 4]


In [26]:
a=np.arange(21)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [28]:
a[0:21:2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [34]:
a[0:20:3]

array([ 0,  3,  6,  9, 12, 15, 18])