In [1]:
import numpy as np

In [2]:
e = np.array([55,89,76,65,48,70])

m = np.array([60,85,60,68,55,60])

c = np.array([65,90,82,72,66,77])

In [3]:
np.greater(e,m)   //three of them get higher score at English

array([False,  True,  True, False, False,  True])

In [7]:
e = np.array([55,89,76,65,48,70])

m = np.array([60,85,60,68,55,60])

c = np.array([65,90,82,72,66,77])

In [8]:
np.greater(m,c)  //all of them get lower score at math

array([False, False, False, False, False, False])

In [9]:
np.greater(e,c)  //all of them get lower score at english

array([False, False, False, False, False, False])

In [ ]:
//ans: all of them get the highest score at chinese
    then three of them get 