In [1]:
import numpy as np

In [5]:
a = np.array(range(30))

In [8]:
a.ravel(order="F")

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [9]:
a.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [15]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [22]:
a.shape

(30,)

In [23]:
a.size

30

In [54]:
a = np.arange(30)
a.resize((5,6),refcheck = False)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [58]:
b = np.array([1,7,13,19,25])
b

array([ 1,  7, 13, 19, 25])

In [59]:
b.flatten()

array([ 1,  7, 13, 19, 25])

In [60]:
for row in b:
  print (row)

1
7
13
19
25
