In [1]:
import numpy as np

In [3]:
A = np.array([[10, 8], [3, 5]])
A

array([[10,  8],
       [ 3,  5]])

In [4]:
np.linalg.inv(A)

array([[ 0.19230769, -0.30769231],
       [-0.11538462,  0.38461538]])

In [5]:
np.linalg.inv(A)@A

array([[1., 0.],
       [0., 1.]])

In [6]:
c , d = np.linalg.eig(A)

In [7]:
c

array([13.,  2.])

In [8]:
d

array([[ 0.93632918, -0.70710678],
       [ 0.35112344,  0.70710678]])

In [10]:
np.linalg.eigvals(A)

array([13.,  2.])

In [14]:
z = np.linalg.svd(A)
z

(array([[-0.91663818, -0.39971796],
        [-0.39971796,  0.91663818]]),
 array([13.94721714,  1.86417116]),
 array([[-0.74319741, -0.6690722 ],
        [-0.6690722 ,  0.74319741]]))